### ISSUE TITLE
Immutable options

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-connector-couchbaseX#120]
https://github.com/Wiredcraft/loopback-connector-couchbaseX/blob/52d46f859474821318e327c4b926312d3eaf5332/lib/couchbaseX.js#L170

https://github.com/Wiredcraft/loopback-connector-couchbaseX/blob/52d46f859474821318e327c4b926312d3eaf5332/lib/couchbaseX.js#L177

I was stuck with a mystery bug about the `options` passed to view changed, and figure out it's was touched(some fields removed) by the code above.

Apparently the low-level library should not alter the parameter passed in, as the lib won't know how the param will be used.

**Comment by xavierchow** [comment]
@ChopperLee2011 could you make a fix?

cc @superbogy @makara

**Comment by ChopperLee2011** [comment]
@xavierchow  I think the idea is: these `options` are handled by former `call() or apply()` method, so remove 'cause it is used and no need later.
I agree the lib should better not update these options, but could you describe your case with more details to let us know why that's wrong. thanks

**Comment by xavierchow** [comment]
https://github.com/Wiredcraft/omni-oms/pull/126/files#diff-3135543a523a8166b2e0e8ef1463b6f7R44-R76
@ChopperLee2011 ^ the `criteria` is used in two places, I have to revert the order of `Object.assign` to avoid it's overridden by the lib.

**Comment by ChopperLee2011** [comment]
this is done, closing
