### ISSUE TITLE
Re-setup the CI badge

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-connector-couchbaseX#90]
The flag would be broken once we changed repo's name I assumed.

_Originally posted by @CCharlieLi in https://github.com/Wiredcraft/loopback-connector-couchbase3/pull/89_

**Comment by superbogy** [comment]
That means we could change the git address. Rename GitHub repository name all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. I think badge will still in work and it should be changed after repo rename and CI run well.
@xavierchow

**Comment by xavierchow** [comment]
@superbogy I'm gonna change the repo name to `loopback-connector-couchbaseX`

**Comment by superbogy** [comment]
done
